
@endpoint = https://ds1n99lv4a.execute-api.us-east-1.amazonaws.com/prod/

GET {{endpoint}}/device
###

POST {{endpoint}}/device
Content-Type: application/json
Accept: application/json

{
    "factoryName":"Wilmington",
    "deviceType":"Furnace",
    "deviceClass":"Furnace",
    "status":"online",
    "ipAddress":"192.168.3.9",
    "name":"Furnace-123"
}

###

DELETE {{endpoint}}/device/720bb7bf-33ef-4a3b-9fc3-7104de7c63c6

###

PUT {{endpoint}}/device/2c5f41cc-33a9-427a-8d65-3f5c6668f967
Content-Type: application/json
Accept: application/json

{
    "deviceAttributes":{
        "maxTemp":"1000C"
    }
}

###